### ISSUE TITLE
【nacos】请问如何用namespace，来管理和区分服务

### ISSUE THREAD

**Issue by zhengqilong** [dyc87112/SpringCloud-Learning#21]
请问如何用namespace，来管理和区分服务？？？

比如这里的opencloud的管理方式是怎么实现的呢
地址：[传送门](http://nacos.didispace.com/nacos/index.html#/configurationManagement?serverId=center&namespace=8f258303-9aa9-46f9-8faa-ce5fefdf8634&edasAppName=&edasAppId=&dataId=&group=&appName=&namespaceShowName=opencloud)
opencloud类的服务全都注册到namespace为opencloud的标签页下，是如何做到的，
我测试过程中发现，所有注册的服务都在Public下，
我的配置 :
```
cloud:
    nacos:
        discovery:
            server-addr: 127.0.0.1:8848
            namespace: 0b4d3de4-b8d9-452d-b1fc-d506be6bfe02
        config:
            server-addr: 127.0.0.1:8848
            file-extension: yml
            namespace: 0b4d3de4-b8d9-452d-b1fc-d506be6bfe02
            group: MYTEST_GROUP
```
